from dtlz_numpy import *
from wfg_numpy import *
from uf_numpy import *
from zdt_numpy import *
from dtlz_torch import *
from wfg_torch import *
from uf_torch import *
from zdt_torch import *
from moo_synthetic_dataset import *